dependent_repositories:
  - name: kogito-runtimes
    branch: setup_dsl
  - name: kogito-apps
    branch: setup_dsl
  - name: optaplanner
    branch: setup_dsl2
  - name: kogito-examples
    branch: setup_dsl  
  - name: kogito-images
    branch: setup_dsl
  - name: kogito-cloud-operator
    branch: setup_dsl

# Full Example
# dependent_repositories:
#   - name: NAME
#     branch: branch_name
#     author:
#       name: another_gh_author
#       credentials_id: another_gh_author_creds
#       token_credentials_id: another_gh_author_creds_token
#     bot_author:
#       name: another_gh_bot_author
#       credentials_id: another_gh_bot_author_creds
  