dependentRepositories:
- name: kogito-runtimes
  branch: 403.2.x
- name: kogito-apps
  branch: 403.2.x
- name: kogito-examples
  branch: 403.2.x
- name: kogito-images
  branch: 403.2.x
- name: kogito-cloud-operator
  branch: 403.2.x
- name: optaplanner
  branch: 407.2.x
